apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: os95v92zm-go 
  janus-idp.io/tekton: os95v92zm-go
  backstage.io/kubernetes-id: os95v92zm-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: os95v92zm-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  