apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: os95v92zm-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: os95v92zm-go 
  name: os95v92zm-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: os95v92zm-go 
